### ISSUE TITLE
ImportError: cannot import name 'NavigationToolbar2Tk'

### ISSUE THREAD

**Issue by hedongya** [mdolab/OpenAeroStruct#267]
Sir or madem, when I run "plot_wing aero.db", I got error shown in the title, could you tell me your matplotlib version, or may you have good advice to fixed this problem?
![default](https://user-images.githubusercontent.com/28126518/52832512-c9b91380-3113-11e9-8ae3-d5d41cdf739c.PNG)

**Comment by hedongya** [comment]
I have solved it after updating matplotlib to 3.0.2 version
